- package-lock.json
- package.json
- postcss.config.js
- src/App.tsx
- src/index.css
- src/index.tsx
- src/pages/Main/Main.tsx
- src/routes/routes.tsx
- tailwind.config.js
- webpack.config.js
> [FE-14] Tailwind 초기세팅

- .eslintrc.js
-children이 없는경우 셀프태그 닫기 설정
내용 관련 린트설정
업습니다.
업습니다.
> [FE-21]chore: 린트 설정

- src/components/Button.tsx
버튼 컴포넌트에서 기본 버튼에 적용되는 props도 적용할 수 있도록 속성을 추가하였습니다.
없음
없음
> [FE-8] fix: 버튼 컴포넌트 props 속성 추가

- src/apis/auth.ts
- src/apis/instance.ts
- src/routes/routes.tsx
- src/utils/localStorage.ts
- tsconfig.extend.json
로컬 스토리지와 Axios 인스턴스 구현
자세한 내용
- interceptor 적용으로 인증이 필요한 인스턴스일 경우 localstorage에서 가져온 token 적용
- 만약 인증 시 에러가 났을 때 401에러면 로그인 창으로 redirect 시킴
- .env 파일에 백엔드 API 주소 추가해야함(vercel env에도 추가해야함)
- **아직 백엔드에서 서버 배포가 아직 안돼서 작동하는지 확인은 못함! 회원가입/로그인 구현하면서 확인할 예정**
- apis/auth 폴더에 인스턴스 사용 예시 넣어둠
없습니다
없습니다
> [FE-37] feat: 로컬 스토리지와 Axios 인스턴스 구현

- src/pages/Login/KakaoButton.tsx
- src/pages/Login/Login.tsx
- 카카오 인가코드 받아오도록 구현
현재 useLocation으로 인가코드를 받아오고 있는데 더 나은 방법이 있을까요ㅠㅠ?
`http://localhost:3000/login?code=코드` 주소에서 받아오고 있습니다!
> [FE-31] feat: 카카오 인가코드 받아오기 구현

- src/pages/Login/GoogleButton.tsx
- src/pages/Login/KakaoButton.tsx
- src/pages/Login/Login.tsx
- 구글 인가코드 받아오도록 구현
- 카카오와 같은 방식으로 url에 code 값으로 받기 때문에 같은 변수명 사용
없습니다
> [FE-32] feat: 구글 인가코드 받아오기 구현

- src/index.css
-기존 tailwind에 preflight설정이 꺼짐으로써 인한버그였음
-그래서 관련해서 index.css에 글로벌 추가
index.css에 글로벌 코드 추가
없습니다.
> [FE-44]style: border사라지는 버그수정

- src/components/MainCategoryTap.tsx
-onSetRecordType함수의 역할이 다양하지 않아 즉시실행 함수로 수정
함수 > 즉시실행함수로 수정
업습니다!
> [FE-41]refactor: 코드 리팩토링

- src/index.css
- [reset.css 블로그](https://parkjh7764.tistory.com/80) 를 참고하여 globalstyle을 적용하였습니다. 
- 기존에 작업했던 내용이 변경되었다면 **다시 적용**하는게 좋을 것 같습니다!
없습니다.
없습니다.
> [FE-54] feat: reset.css를 GlobalStyle로 적용

- src/components/Chip.tsx
- src/pages/AddRecord/AddRecord.tsx
-칩 컴포넌트 구현완료
-props로는 interface정리한거 참조 부탁드려요
자유롭게 부탁드립니다~
> [FE-47]feat: 칩 컴포넌트구현

- src/App.tsx
- src/pages/NotFound/NotFound.tsx
-notFound페이지에 UseNavigate안먹는 버그> Link로 수정
> fix:Router오류 수정

- src/components/Button.tsx
- src/components/Chip.tsx
- src/components/MainCategoryTap.tsx
- src/index.css
- src/pages/AddRecord/AddRecord.tsx
- src/pages/AddRecord/AddRecordCategory.tsx
- src/pages/AddRecord/AddRecordFile.tsx
- src/pages/AddRecord/AddRecordIcon.tsx
- src/pages/AddRecord/AddRecordInput.tsx
- src/pages/AddRecord/AddRecordTextArea.tsx
* Button,Chip 컴포넌트 props추가 (type)
* 전체적인 레이아웃 맞추기
* 태일윈드 프로퍼티로 썼던 색깔들 theme설정한 값으로 수정
* input이나 textarea에 글자수 0개일때 버그 수정
* 카테고리 컴포넌트 선택에 따른 active 적용
전체적인 코드스타일 리뷰 부탁드려려요!!!!
> [FE-45]컴포넌트 리팩토링, 페이지 레이아웃 구현

- src/apis/auth.ts
- src/apis/instance.ts
- src/index.tsx
- src/pages/Login/[type].tsx
- src/pages/SignUp/SignUp.tsx
- src/react-query/hooks/useAuth.ts
- src/react-query/hooks/useNickname.ts
- 회원가입 기능 구현
- 아래 로직으로 주소에서 query가져옴
```js
const useQuery = () => {
const { search } = useLocation()
return React.useMemo(() => new URLSearchParams(search), [search])
}
```
없습니다.
> [FE-63] feat: 회원가입 기능 구현

- src/pages/DetailRecord/DetailRecord.tsx
- src/pages/DetailRecord/getCreatedDate.ts
- 작성 날짜 전환 로직 구현
- 1분 이내는 몇초전으로 표기, 1시간 이내는 몇분전으로 표기, 1일 이내에는 몇시간전으로 표기, 24시간 이후에는 작성된 날짜시간 표기
- 없음
- 없음
> [FE-69] feat: 날짜 전환 로직 구현

- src/pages/MyRecord/MyRecord.tsx
- src/pages/NotService/NotService.tsx
- src/pages/Rank/Rank.tsx
- src/pages/Setting/Setting.tsx
-임시로 페이지내에서 마운트시 페이지 이동하도록 설정
https://user-images.githubusercontent.com/103626175/210177498-a817ad17-32fd-4850-98ad-4bc265b4d297.mov
> [FE-65]feat:준비중 페이지와 연결

- src/components/Chip.tsx
- 크기가 default일 경우와 small일 경우 아래 사진처럼 다르게 표시되도록 다시 구현하였습니다.
- 디자인 시스템에서 더 적용할 부분이 있을까요?
> [FE-78] feat: pointer, property 타입 추가

- src/pages/SignUp/SignUp.tsx
- 닉네임 정규식 체크 부분에서 빠진 자음/모음 부분 추가하였습니다.
- 이 부분 제외하고 QA이슈는 #58 에서 추가해서 이미 반영되었습니다.
X
없습니다
> [FE-84] fix: 닉네임 정규식 체크, 자음/모음 정규표현식 추가

- src/apis/share.ts
- src/components/Button.tsx
- src/pages/DetailRecord/DetailRecord.tsx
- src/pages/DetailRecord/ReplyInput.tsx
- src/pages/DetailRecord/ShareModal.tsx
- 공유하기 모달 ui 에러 수정
- 버튼 컴포넌트 children 속성 추가
- 상세 페이지 ui 퍼센테이지로 수정
- 없음
- 없음
> [FE-83] fix: 상세페이지, 모달 UI 에러 수정

- src/components/Layout.tsx
- src/components/Navbar.tsx
- src/pages/AddRecord/AddRecord.tsx
- src/pages/Login/GoogleButton.tsx
- src/pages/Login/KakaoButton.tsx
- src/pages/Login/Login.tsx
-요구사항에 맞게 420픽셀까지는 100% 그 이후는 배경색으로
-다른 페이지들도 같이 리팩토링
자유롭게 의견 부탁드립니다
> [FE-79]feat: 레이아웃 리팩토링

- src/apis/record.ts
- src/pages/AddRecord/AddRecord.tsx
- src/pages/AddRecord/AddRecordCategory.tsx
- src/pages/AddRecord/AddRecordFile.tsx
-categoryData 백엔드에서 준 데이터로 생성
-any 삭제
-type 추가
클린코드나 자유롭게 리뷰 부탁드립니다.
> [FE-74]refactor : 코드 리팩토링

- src/pages/DetailRecord/DetailRecord.tsx
- 머지하면서 주석처리된 editModal state 주석 제거
- 없음
- 없음
> fix : 상세 페이지 editmodal state 주석 제거

- src/pages/DetailRecord/EditModal.tsx
- src/pages/DetailRecord/ReplyInput.tsx
- 레코드 글자수 제한 변경 (200 -> 100)
- 이미지 삽입 카메라 버튼 0/1개 선택 시 플러스 활성화, 1/1개 선택 시 플러스 비활성화
- 레코드 삭제 메시지창 변경 (alert -> confirm)
- 없음
- 없음
> [FE-88] feat: 글자수 제한, 사진업로드시 아이콘 변경, 레코드 삭제 메시지창 변경

- src/components/Button.tsx
- src/pages/Login/GoogleButton.tsx
- src/pages/Login/KakaoButton.tsx
- src/pages/Login/Login.tsx
- src/pages/SignUp/SignUp.tsx
- 닉네임 정책 변경으로 인한 닉네임 조건 변경
- 버튼 w-full로 변경
> [FE-89] 닉네임 정책 변경으로 인한 코드 수정

- src/pages/AddRecord/AddRecordColor.tsx
> [FE-91] fix: props -> Props로 변수명 픽스

- src/pages/AddRecord/AddRecordCategory.tsx
-기존에 백에 의존된 코딩이 날라가서 다시 고쳐서 올림
현재 잘 됩니다
> fix: 카테고리 백 의존성 버그

- src/pages/Main/Main.tsx
- src/pages/MyRecord/MyRecord.tsx
- src/pages/Rank/Rank.tsx
- src/pages/Setting/Setting.tsx
- NavBar 탭에 Notservice 디자인 적용
- 우선 나중에 구현될 화면이기 때문에 하드코딩으로 넣었습니다!
없습니당~
> [FE-105] feat: NavBar 탭에 Notservice 디자인 적용

- src/pages/AddRecord/AddRecord.tsx
-sticky를 이용해서 하단에 고정
https://user-images.githubusercontent.com/103626175/211978897-e571e759-990a-4a96-a2bd-e9dbbe3f3744.mov
> [FE-100]feat: 레코드 추가 버튼 하단 고정

- src/pages/DetailRecord/ReplyList.tsx
- src/pages/DetailRecord/getCreatedDate.ts
- 날짜 전환 표기 로직 에러 수정
- day 표기 로직 추가 (게시물 작성 일주일 미만)
- 없음
- 없음
> fix : 날짜 전환 표기 로직 수정

- src/components/MainCategoryTap.tsx
- src/pages/AddRecord/AddRecord.tsx
> [FE-94]feat: 축하 위로 탭 디자인 재적용

- README.md
- 우선 1차로 작업했고 우선 머지 후에 더 작업하겠습니다!
추가로 넣었으면 하는 점 댓글 부탁드려요!
우선 + RecordIt Organization에 우리 서비스가 무엇인지를 적고
프론트 백 각자의 레파지토리에서는 기술 위주로 적는 것이 좋을 것 같다고 생각했습니다. 의견있으면 댓글 부탁드려욤
> [FE-103] feat: README 1차 수정

- src/hooks/useImageSwipe.ts
> fix: 상세 페이지 이미지 스와이프 에러 해결

- src/apis/auth.ts
- fix: ouah_token CamelCase로 변경
> [FE-108] fix: ouah_token CamelCase로 변경

- src/apis/auth.ts
- src/react-query/hooks/useAuth.ts
-  register_session CamelCase로 변경
> [FE-108] fix: register_session CamelCase로 변경

- src/apis/auth.ts
- src/react-query/hooks/useAuth.ts
- release & fix: 배포 테스트를 위해서 빠른 버그 픽스
> [develop] release & fix: 배포 테스트를 위해서 빠른 버그 픽스

- src/pages/AddRecord/AddRecord.tsx
-백엔드와 연동해서 사진추가가 반영되도록 코드 리팩토링
-기존에 Blob안에 내용을 담아서 주던걸 files 그대로 전송
> [FE-107]refactor: 사진추가 반영되도록 코드 리팩토링

- src/components/Modal.tsx
- src/hooks/useClickOutside.ts
> [FE-101] style: 변수명 수정

- package-lock.json
- package.json
- src/assets/constant/RecordIcons.ts
- src/assets/front.svg
- src/index.css
- src/pages/AddRecord/AddRecord.tsx
- src/pages/AddRecord/AddRecordColor.tsx
- src/pages/AddRecord/AddRecordIcon.tsx
-기능 구현
-전역에 slider관련 css추가
-className에 !가 붙은거는 important써주기 위함
-라이브러리 추가
자유롭게 주세용~
> [FE-96]feat: 아이콘 슬라이더 구현

- src/apis/reply.ts
- src/pages/DetailRecord/DetailRecord.tsx
- src/pages/DetailRecord/ReplyInput.tsx
- 댓글 작성 구현
- 현재 이미지와 사진을 같이 올려야만 전송이 되는 에러가 있는데 백엔드 로직 변경이 되면 해결될 예정임
- 없음
- 없음
> [FE-103] feat: 댓글 작성 구현

- src/pages/AddRecord/AddRecord.tsx
- src/pages/AddRecord/AddRecordFile.tsx
-똑같은 사진 다시 올릴 수 없는 버그 수정
-사진을 지웠어도 데이터가 남아있는 버그 수정
> [FE-110]bug: 사진 업로드 버그 수정

- src/components/Button.tsx
- src/components/Loading.tsx
- src/components/Spinner.tsx
- src/pages/Login/[type].tsx
- src/pages/SignUp/SignUp.tsx
- src/react-query/hooks/useAuth.ts
- spinner 버튼에 로딩 적용
- spinner 컴포넌트 size 를 임시로 small, medium, large 세가지로 분류, 디자인이 픽스되면 다시 변경 예정
- 로그인/회원가입 로딩 컴포넌트와 Spinner 적용
없습니당
> [FE-99] 로그인/회원가입 로딩 컴포넌트와 Spinner 적용

- src/apis/record.ts
- src/apis/recordData.ts
- src/apis/reply.ts
- src/hooks/useIntersectionObserver.ts
- src/hooks/useThrottle.ts
- src/pages/DetailRecord/DetailRecord.tsx
- src/pages/DetailRecord/ReplyInput.tsx
- src/pages/DetailRecord/ReplyItem.tsx
- src/pages/DetailRecord/ReplyList.tsx
- src/pages/DetailRecord/getChipIconName.ts
- src/types/replyData.ts
- 댓글 작성 : react query useQuery로 리팩토링
- 댓글 조회 : react query infinitequery로 구현
- 무한스크롤 : IntersectionObserver API 로 구현 [https://developer.mozilla.org/ko/docs/Web/API/IntersectionObserver](https://developer.mozilla.org/ko/docs/Web/API/IntersectionObserver)
- 쓰로틀이랑 고민하다가 일단 저걸로 구현했는데 고민중이라서 쓰로틀 로직 아직 안지움..🥲
- 없움
- 뭐가 좋을지?
> [FE-58] feat: 댓글 작성 구현 & 무한스크롤 구현 및 리액트 쿼리로 로직 리팩토링

- src/pages/AddRecord/AddRecordTextArea.tsx
> [FE-112]refactor: 텍스트창 색깔 바뀜수정

- src/pages/AddRecord/AddRecordFile.tsx
> [FE-102]refactor: 이미지 1:1비율로 생성도되록

- src/components/Button.tsx
- src/components/Spinner.tsx
> [FE-116] style: Spinner 디자인 시스템 적용

- src/components/BackButton.tsx
- src/components/Navbar.tsx
- src/pages/AddRecord/AddRecord.tsx
- src/react-query/hooks/useUser.ts
- src/routes/protectedRoute.tsx
- src/routes/router.tsx
- NavBar에 있는 내용 ProtectedRoute로 리팩토링
- 레코드 추가 페이지에서 뒤로가기 시 알럿 노출
없습니다
> [FE-115] 레코드 추가 페이지에서 뒤로가기 시 알럿 노출

- src/pages/DetailRecord/ReplyList.tsx
- 무한 스크롤 계속 함수 호출되는 에러 수정
- 테스트용 버튼 삭제
- 없음
- 없음
> Fix: 무한 스크롤 에러 수정

- src/pages/AddRecord/AddRecord.tsx
- src/pages/AddRecord/AddRecordIcon.tsx
-이전에 리팩토링하면서 onClick데이터 사라진 부분 다시 추가
> [FE-117]fix: icon들 클릭했을떄 적용안되는 버그 수정

- src/apis/instance.ts
- Axios instance에 timeout 적용
없습니다
- 임시로 5000, 즉 5초로 했는데 괜찮나요?
> [FE-120] feat: Axios instance에 timeout 적용

- src/components/Alert.tsx
- src/pages/AddRecord/AddRecord.tsx
- src/pages/DetailRecord/ReplyInput.tsx
- src/routes/protectedRoute.tsx
-Alert 컴포넌트 subMessage ReactNode로 수정
여기서 작업중인 내용이 모두 삭제됩니다 처럼 색깔이 들어갈 수도 있어서 ReactNode로 변경했습니다
없습니다
> [FE-121] refactor: Alert 컴포넌트 subMessage ReactNode로 수정

- src/apis/share.ts
- 공유하기 주소 어떤 url에서도 /record/${id} 주소가 공유되도록 변경
> [FE-125] fix: 공유하기 주소 변경

- src/assets/constant/RecordIcons.ts
> [FE-126] fix: 아이콘 이름 모두 소문자로 변경

- src/pages/AddRecord/AddRecordIcon.tsx
> [fix] fix: src안바뀌는 버그

- src/pages/DetailRecord/ImageContainer.tsx
- src/pages/DetailRecord/ReplyInput.tsx
- 레코드 상세 페이지에서 댓글 클릭시 Alert 작업과 1:1비율 재설정
> [FE-127] 레코드 상세 페이지에서 댓글 클릭시 Alert 작업과 1:1비율 재설정

- src/pages/AddRecord/AddRecord.tsx
- fix: 레코드 추가 실패할 경우 로딩 재적용
- 실패 시 alert 보여주기
> [FE-128] fix: 레코드 추가 실패할 경우 로딩 재적용

- src/pages/AddRecord/AddRecordTextArea.tsx
> [FE-129]fix: 200자이상 입력가능 버그 수정

- src/pages/DetailRecord/EditModal.tsx
- EditModal 모달 밖 클릭 시 닫아지도록 구현
> [FE-132] feat: EditModal 모달 밖 클릭 시 닫아지도록 구현

- src/assets/constant/RecordInputs.ts
- src/pages/AddRecord/AddRecord.tsx
- src/pages/AddRecord/AddRecordIcon.tsx
- src/pages/AddRecord/AddRecordInput.tsx
- src/pages/AddRecord/AddRecordTextArea.tsx
-파일 전송이 안되는 버그 수정
-아이콘 스크롤부분 QA에 맞게 수정
-아이콘 좌우버튼 클릭시 실 적용 안되는 버그 수정
https://user-images.githubusercontent.com/103626175/213082454-cd68c3a8-b0b2-46e5-a544-ebee455ac339.mov
일단 지금 세션문제떄문에 파일추가되는지는 확인인 불가능해서 스크롤 부분만 올려요!
> [FE-131]refactor: QA 디테일레코드 부분 반영

- src/pages/AddRecord/AddRecord.tsx
-레코드 작성후 확인버튼을 클릭하면 다중클릭되는 버그를 수정했습니다.
화면으론 잘 안보이는데 동시에 한 2번 클릭한거에요! 사진 참고해주세영
> [FE-147]fix: 중복 클릭되는 버그 수정

- src/components/Toast.tsx
- src/pages/AddRecord/AddRecord.tsx
-기존 Modal사용해서 토스트 컴포넌트 구현
https://user-images.githubusercontent.com/103626175/213222850-20b267a7-54d4-459f-95a0-b443b7ca9b99.mov
자유롭게 리뷰 부탁드립니다.
> [FE-134]feat: 토스트 컴포넌트 구현

- src/pages/AddRecord/AddRecordFile.tsx
-사진 다중선택 가능하도록
-파일이 3개이상일때 업로드 불가능하도록
자유롭게 주세요~
> [FE-145]feat: 사진 다중 선택

- src/pages/AddRecord/AddRecordCategory.tsx
-클라이언트에 의존적인 카테고리데이터 서버의존적으로 이관
널처리 잘했는지 한번 확인 부탁드려용~
> [FE-137]refactor: 코드 리팩토링

- src/hooks/useThrottle.ts
- src/pages/AddRecord/AddRecordIcon.tsx
-기존 코드에서 훅을 사용해서 코드 실행
-useThrottle 잘못구현된거 수정
자유롭게 주세용~
> [FE-138]refactor: 훅 사용해서 쓰로틀링구현

- src/pages/AddRecord/AddRecord.tsx
- src/pages/AddRecord/AddRecordFile.tsx
-레코드 추가페이지에 적용
-레코드 추가페이지에 디폴트로 적용되있던것 삭제
자유롭게 주세용~
> [FE-133]feat: 댓글 사진 5MB추가시 Toast창 띄워주기

- src/components/Alert.tsx
- onCancel과 subMessage 없을 경우에 디자인 수정
> [FE-151] refactor: Alert 컴포넌트 리팩토링

- src/apis/reply.ts
- src/assets/constant/constant.ts
- src/assets/detail_page_icon/arrow_down.svg
- src/assets/detail_page_icon/arrow_up.svg
- src/index.css
- src/pages/DetailRecord/DetailRecord.tsx
- src/pages/DetailRecord/NestedReplyList.tsx
- src/pages/DetailRecord/ReplyInput.tsx
- src/pages/DetailRecord/ReplyItem.tsx
- src/pages/DetailRecord/ReplyList.tsx
- src/store/atom.ts
- src/types/replyData.ts
- tailwind.config.js
- 대댓글 조회 / 작성 구현
- 전체 폰트 적용 방법 변경
- 없습니다
> [FE-114] feat: 대댓글 조회/작성 구현

- src/apis/record.ts
- src/pages/DetailRecord/DetailRecord.tsx
- src/pages/DetailRecord/EditModal.tsx
-실제 서버에 삭제되는것 제외한 구현
-백엔드 api와 연동후 실제 삭제까지 적용
자유롭게 리뷰 부탁드려용~
> [FE-140]feat: 레코드 삭제버튼 구현

- src/pages/DetailRecord/ReplyItem.tsx
- src/pages/DetailRecord/ReplyList.tsx
- src/pages/MyRecord/MemoryRecordItem.tsx
- src/types/replyData.ts
- 추억레코드에서 댓글 클릭 시 해당 댓글로 스크롤 이동
- 상세페이지 댓글 컴포넌트들을 조금 수정하였기 때문에 확인하고 충돌 나는지 확인할 것
없습니다
> [FE-149] feat: 나만의 추억 레코드 

- src/hooks/useImageSwipe.ts
- 상세 페이지 이미지 컨테이너 에러 수정
- 없음
- 없음
> fix: 상세 페이지 이미지 컨테이너 에러 수정

- README.md
> [FE-154] etc: README 추가

- src/components/Layout.tsx
- src/pages/MyRecord/MemoryRecordItem.tsx
- [design: cursor-pointer 필요한 부분에만 적용](https://github.com/ItRecode/recodeIt-client/commit/f826ac25d6d0ce045dd88bc49ee8d8b5c11a788d)
- 전역 백그라운드 색깔 grey로 변경
> [FE-155] style: 마이 레코드 커서 포인터 재적용

- src/pages/AddRecord/AddRecord.tsx
> [FE-157]fix: url로 화면 빠져나갈때 수정모드 안지워지는 버그

- src/pages/MyRecord/MemoryRecordItem.tsx
> [FE-158] feat: 추억 레코드 댓글이 없을 경우 UI 구현

- src/components/Alert.tsx
- src/pages/DetailRecord/DetailRecord.tsx
- src/pages/DetailRecord/EditModal.tsx
-삭제 버튼을 누르고 알럿창을 눌러야 삭제가 되야하는데 삭제버튼만 눌러도 삭제되는 버그수정
-알럿 디자인 수정
-알럿창 버튼 두개일때 사이에 줄 추가
> [FE-163]refactor: 삭제 리팩토링,style: 알럿창 버튼 두개일때 사이에 줄 추가

- src/pages/AddRecord/AddRecordFile.tsx
- src/pages/DetailRecord/DetailRecord.tsx
- src/pages/DetailRecord/ImageContainer.tsx
-사진갯수가 0개여도 다음버튼 활성화되는 버그 수정
-사진 제대로 삭제 안되는 버그 수정
세인트코드도 수정했어용~
> [FE-162]fix: 사진 제대로 삭제 안되는 버그 수정, 사진갯수가 0개여도 다음버튼 활성화되는 버그 수정

- src/pages/AddRecord/AddRecordFile.tsx
> fix: 레코드 추가페이지 버그 수정

- src/pages/AddRecord/AddRecord.tsx
- 이부분 혹시나 다시 바뀔수도있어서 sticky관련 로직남겨둘게요!
작업내용처럼 sticky관련 로직 남겨뒀어요.
그리고 실제 sticky적용하는 로직 273번쨰 줄도 ${}안에 부분 뺴도되는데 그러면 린트에러걸려서 일부러 block으로 남겨뒀어요!
> [FE-164]style: 레코드 추가하기 버튼 sticky 제거

- src/pages/MyRecord/MyRecordCalendar.tsx
- src/pages/MyRecord/TodayRecord.tsx
- src/react-query/hooks/useMyRecord.ts
-  오늘 레코드가 변경되었을 때 데이터 refetch 구현
> [FE-166] fix: 오늘 레코드가 변경되었을 때 데이터 refetch 구현

- public/index.html
- src/apis/reply.ts
- src/apis/share.ts
- src/pages/DetailRecord/DetailRecord.tsx
- src/pages/DetailRecord/NestedReplyList.tsx
- src/pages/DetailRecord/ReplyInput.tsx
- src/pages/DetailRecord/ReplyItem.tsx
- src/pages/DetailRecord/getCreatedDate.ts
- src/store/atom.ts
- 공유하기 이미지 추가
- 수정버튼 에러 수정
- 답글 작성후 자동으로 답글리스트 열리기 수정
- 이미지 추가 에러 수정
- 없음
- 없음
> [FE-136] feat: 공유하기 form 추가

- public/index.html
- fix: title, description 공백 제거
> [fix] fix: title, description 공백 제거

- src/apis/reply.ts
- src/apis/share.ts
- src/components/BackButton.tsx
- src/components/Chip.tsx
- src/pages/DetailRecord/DetailRecord.tsx
- src/pages/DetailRecord/NestedReplyList.tsx
- src/pages/DetailRecord/ReplyInput.tsx
- src/pages/DetailRecord/ReplyItem.tsx
- src/pages/DetailRecord/ShareModal.tsx
- src/store/atom.ts
- 댓글/답글 수정 기능 추가
- 본인 레코드 본인 댓글 삭제 버튼 노출
- 카카오톡 공유 이미지 추가
- 링크 공유로 상세 페이지 진입시 뒤로가기 누르면 메인화면으로 이동
- 비회원 상태에서 인풋창 누를 때 키보드 노출X
- 칩 디자인 수정
- 칩 수정했는데 미묘하게 안맞는것 같기도 하고...
- 없음
> [FE-161] feat: 댓글 수정 추가, QA 버그 수정

- src/pages/MyRecord/MemoryRecordItem.tsx
- design: 추억 레코드 댓글 없을 때 멘트 변경
> [FE-169] design: 추억 레코드 댓글 없을 때 멘트 변경

- src/pages/NotFound/NotFound.tsx
> [FE-170] design: 레코딧으로 이동 버튼 디자인 수정

- src/pages/AddRecord/AddRecord.tsx
- src/pages/DetailRecord/DetailRecord.tsx
- src/pages/DetailRecord/NestedReplyList.tsx
- src/pages/DetailRecord/ReplyInput.tsx
- src/pages/DetailRecord/ReplyItem.tsx
> [FE-172] feat: 엔터키 구현, 답글 수정 구현

- src/pages/AddRecord/AddRecord.tsx
- src/pages/AddRecord/AddRecordCategory.tsx
- src/pages/AddRecord/AddRecordColor.tsx
- src/pages/AddRecord/AddRecordIcon.tsx
- src/pages/AddRecord/AddRecordInput.tsx
- src/store/atom.ts
-칩 이모지랑 멘트 맞추기
-카테고리 변경할 때 아이콘 선택박스 default값에 고정되게 변경
지금 수정 접근시 카테코리가 안바뀌는 버그가 잘 안고쳐져서 일단 한거만큼 풀리퀘 올리고 새로 이슈파서 할게요
> [FE-167]fix: QA에러 수정

- src/pages/DetailRecord/ReplyItem.tsx
> fix: 답글 화살표 에러 수정

- src/pages/DetailRecord/DetailRecord.tsx
> [FE-174]feat: 레코드 삭제시 마이레코드로 이동

- src/pages/AddRecord/AddRecordTextArea.tsx
- src/pages/DetailRecord/ReplyInput.tsx
> fix: 수정모드일때 br 태그 수정

- src/pages/AddRecord/AddRecord.tsx
-수정페이지 이동했을때 변경안하면 보라색으로 바뀌는거 해결
> [Fe-175]fix: 수정페이지 이동했을때 변경안하면 보라색으로 바뀜

- src/pages/AddRecord/AddRecordCategory.tsx
- 레코드 추가후 수정했을때 카테고리 적용안되는 버그해결 위해 useEffect에 의존성 추가
> [FE-171]fix: 레코드 추가후 수정했을때 카테고리 적용안되는 버그

- src/pages/MyRecord/MemoryRecordItem.tsx
- 마이레코드 br태그 나오는 버그 수정
- 엔터 반영하면 디자인 이상할거 같아서 반영안함
- 없음
- 없음
> fix: 마이레코드 br 태그 버그 수정

- src/pages/AddRecord/AddRecord.tsx
- src/pages/AddRecord/AddRecordTitle.tsx
> [FE-176]feat: 수정모드일때 제목 색깔 변경

- src/pages/AddRecord/AddRecordFile.tsx
> [FE-177]fix: 수정접근하고 사진 삭제하고 다시추가하면 추가된게 이미지로 안보임

- src/pages/AddRecord/AddRecord.tsx
- design: 레코드 추가/수정 실패 시 멘트 변경
> [fix] design: 레코드 추가/수정 실패 시 멘트 변경

- package-lock.json
- package.json
- src/pages/DetailRecord/DetailRecord.tsx
- 뒤로가기, 앞으로가기시 input 모드 데이터 남아있는 버그 수정
- 없음
- 없음
> hotfix : 뒤로가기, 앞으로가기시 input 모드 데이터 남아있는 버그 수정

- package-lock.json
- package.json
- src/pages/AddRecord/AddRecord.tsx
- src/pages/DetailRecord/DetailRecord.tsx
- hotfix : 뒤로가기 앞으로가기시 input 모드 데이터 남아있는 버그 수정
> [develop] hotfix : 뒤로가기 앞으로가기시 input 모드 데이터 남아있는 버그 수정

- src/apis/reply.ts
- src/hooks/useScrollCommentId.ts
- src/pages/DetailRecord/InputAddImage.tsx
- src/pages/DetailRecord/InputSnackBar.tsx
- src/pages/DetailRecord/NestedReplyItem.tsx
- src/pages/DetailRecord/NestedReplyList.tsx
- src/pages/DetailRecord/ReplyInput.tsx
- src/pages/DetailRecord/ReplyItem.tsx
- src/pages/DetailRecord/ReplyList.tsx
- src/react-query/hooks/useGetReply.ts
- 답글 삭제 버그 수정
- 답글 리스트 열기 버그 수정
- 리팩토링 중 갑작스러운 버그 발견으로 핫픽스 진행하여 컴포넌트 분리작업 조금 되어있음
- 없음
- 없음
> hotfix: 답글 삭제 버그 수정, 답글열기 버그 수정

- public/index.html
> [FE-185]feat: GA심기

- src/pages/DetailRecord/ReplyInput.tsx
- input placeholder 두줄 버그 수정
- screen width 340px 이하 `(100자 이내)` 멘트 삭제
- 
- 없음
- 없음
> fix: input placeholder 두줄 버그 수정

- src/pages/AddRecord/AddRecordFile.tsx
-다시 파일 다중 추가 되도록
-추가시 url 반영안되는 버그 수정
> [FE-178]refactor: 파일 다중 추가, 추가시 UI반영 안되는 버그 수정

- src/pages/AddRecord/AddRecordFile.tsx
> [FE-186]fix: 탭변경시 사진 초기화 안되는 버그

- src/pages/DetailRecord/DetailRecord.tsx
- src/pages/NotRecord/NotRecord.tsx
- src/routes/router.tsx
-기존 디테일페이지에서 삭제된 레코드를 받을 시 notRecord페이지로 이동
-notRecord페이지 개발
> [FE-188]feat: notRecord페이지

- src/pages/DetailRecord/InputTextarea.tsx
- src/routes/protectedRoute.tsx
> [FE-190] design: 회원가입 문구 로그인으로 변경

- src/apis/record.ts
- src/pages/Main/Main.tsx
- src/pages/Main/MixRecord.tsx
- src/pages/Main/Together.tsx
- src/pages/Main/TogetherSlider.tsx
- src/types/recordData.ts
- 믹스 레코드 기눙 구현
https://user-images.githubusercontent.com/88193063/216807729-bab6a8b9-a89c-4062-9b19-783b3c9b6a05.mov
- 없음
> [FE-181] feat: 믹스레코드 기능 구현

- src/components/Navbar.tsx
- src/pages/Main/MixRecord.tsx
- src/pages/Main/TogetherSlider.tsx
> [fix] style:  홈화면 디자인 스타일 재구성

- src/pages/Main/Main.tsx
- src/pages/Main/Together.tsx
- src/pages/Main/TogetherSlider.tsx
- 이미지 링크 추가
- 탭 패딩 추가
- 글자수 변경, 둘째줄 앞자리 공백시 공백 제거
- 없음
- 없음
> hotfix: 탭 padding 추가, 이미지 링크 추가, 글자수 변경

- src/hooks/useCheckMobile.ts
- src/pages/Main/TogetherSlider.tsx
- 함께 축하해보세요 댓글 나누는 기능 모바일 감지 추가
- 없음
- 없음
> hotfix: 모바일 감지 추가

- src/assets/constant/constant.ts
- src/hooks/useCheckMobile.ts
- src/pages/Main/Main.tsx
- src/pages/Main/MixRecord.tsx
- src/pages/Main/Together.tsx
- src/pages/Main/TogetherSlider.tsx
- src/pages/Main/TogetherTab.tsx
- src/types/category.ts
- 믹스레코드 빈 태그 발생되는 버그 수정
- 데이터 refetch 방지
- 카테고리 ID 상수, 타입 추가
- 없음
- 없음
> [FE-195] fix: 믹스레코드 버그 수정

- src/pages/Main/Main.tsx
- fix: 브라우저 작아졌을 때 스크롤 에러 버그 픽스
- `w-full, h-full` 속성으로 감싸져있던 부분 때문이었습니다.. -> 왜 안되었던건지는 잘 모르겠습니다ㅠ
> [FE-212] fix: 브라우저 작아졌을 때 스크롤 에러 버그 픽스(feat. 메인페이지)

- src/pages/MyRecord/Common/MemoryRecordCard.tsx
- src/pages/MyRecord/MemoryRecord.tsx
- src/types/recordData.ts
- style: iconColor 필드 이름 변경으로 colorName으로 수정
-
> [FE-218] fix: iconColor 필드 이름 변경으로 colorName으로 수정

- src/assets/collect_page_icon/scrollTop.svg
- src/pages/Collect/Collect.tsx
- src/pages/Collect/RecentRecord.tsx
- src/react-query/hooks/useRecentRecord.ts
- src/utils/getCurrentTime.ts
-새로고침시 화면 상단에 고정안되는 버그 수정
-새로고침시 시간 초기화 안되는 버그 수정
-scrollTop 버튼 구현
자유롭게 리뷰 부탁드립니다
> [FE-220]fix,feat: 스크롤 탑버튼 구현, 모아보기 버그 수정

- src/apis/record.ts
- src/assets/ranking_btn_arrow.svg
- src/assets/ranking_down_arrow.svg
- src/components/Category.tsx
- src/pages/Main/Ranking.tsx
- src/pages/Main/RankingList.tsx
- src/types/recordData.ts
> [FE-194] feat: 메인페이지 랭킹

- src/components/RecordCard.tsx
- src/pages/Collect/Collect.tsx
- src/pages/Collect/RecentRecord.tsx
- src/pages/Main/TogetherSlider.tsx
-유저가 서비스 닫았을시 새로고침 리셋
-카드 크기 고정값해제
-새로고침시 깜빡임 해결
-스크롤 버튼 조정
자유롭게 부탁드립니다!
> [FE-221]fix: QA버그 수정

- src/assets/constant/collect.ts
- src/pages/Collect/RecentRecord.tsx
- src/pages/Collect/Timer.tsx
- src/utils/getTimeGap.ts
-타이머 UI개발
-최근 레코드 서브텍스트 변경
추상화 잘한거같은데 과감하게 리뷰남겨주세요
> [FE-222]feat: 타이머 UI개발

- src/pages/AddRecord/AddRecordCategory.tsx
> fix: 축하, 위로 카테고리 코드 바뀐버그 수정

- src/components/Category.tsx
- src/components/RankingItem.tsx
- src/components/RecordCard.tsx
- src/pages/Collect/CollectRanking.tsx
- src/pages/DetailRecord/InputAddImage.tsx
- src/pages/DetailRecord/ReplyInput.tsx
- src/pages/Main/MixRecord.tsx
- src/pages/Main/RankingList.tsx
- 믹스레코드 : 댓글 한 줄에 15자까지 노출, 3줄까지 노출
- 함께 축하해보세요! : 웹/모바일 관련 없이 모두 6글자 줄바꿈
- 홈/모아보기 - 랭킹 :  스와이프 후 위로 레코드 이동 시 스와이프 초기화
- 홈/모아보기 랭킹 : 10번 디자인 수정(세로 정렬)
- 랭킹 : 더보기 데이터 없을시 더보기 버튼 노출 X
- 상세 페이지 : 댓글 5MB 이상 이미지 업로드 금지 기능 추가
- 없음
- 없음
> [FE-223] fix: QA 피드백 반영 및 추가

- src/pages/Collect/Timer.tsx
> [FE-225]fix: 타이머 버그 픽스

- src/pages/Collect/RecentRecord.tsx
- src/react-query/hooks/useRecentRecord.ts
> [FE-227]fix: 새로고침시 상단으로 안가는 버그

- src/components/RecordCard.tsx
- src/pages/Collect/RecentRecord.tsx
- src/pages/Collect/Timer.tsx
- src/pages/DetailRecord/DetailRecord.tsx
- src/react-query/hooks/useRecentRecord.ts
-이전페이지를 기억후 최근레코드로 화면이동
-시간 크기 변경되지 않도록
-새로고침시 최상단으로 가는 버그 픽스
첫번쨰 기능 설명필요하시거나 더 좋은방법 있으면 말씀해주세요~
> [FE-228]fix,feat: 최근 레코드 QA반영

- src/components/RecordCard.tsx
- 최신레코드 레코드 아이템 크기 조정 이슈 해결
- 없음
- 없음
> fix: 최신레코드 레코드 아이템 크기 조정 이슈 해결

- src/components/RankingItemNoData.tsx
- src/pages/Collect/CollectRanking.tsx
- src/pages/Main/RankingList.tsx
> [FE-247] feat: 랭킹 데이터 없는 경우 추가

- src/pages/DetailRecord/InputTextarea.tsx
- src/pages/DetailRecord/ReplyInput.tsx
> [FE-248] fix: 수정모드일때 value 바뀌는 기능 추가

- src/assets/front_white.svg
- src/pages/Setting/FeedbackMail/FeedbackMail.tsx
- src/pages/Setting/ManageComment/ManageComment.tsx
- src/pages/Setting/ModifyInfo/ModifyInfo.tsx
- src/pages/Setting/Setting.tsx
- src/pages/Setting/SettingSection.tsx
- src/pages/Setting/TeamIntroduction/TeamIntroduction.tsx
- src/pages/Setting/Withdraw/Withdraw.tsx
- src/routes/router.tsx
-기타 페이지 라우팅
-설정페이지 개발
자유롭게 리뷰 부탁드립니다!!!
> [FE-203]feat: 설정페이지 레이아웃 개발 기타 페이지 라우팅

- src/apis/myRecord.ts
- src/pages/DetailRecord/DetailRecord.tsx
- src/react-query/hooks/useMemoryRecord.ts
- src/react-query/hooks/useMyRecordByDate.ts
- src/types/myRecord.ts
> [FE-235]  fix: 오늘레코드 api 변경으로 연동 구현 수정

- src/pages/Setting/FeedbackMail/FeedbackMail.tsx
> [FE-233] feat: 피드백메일 레이아웃

- package-lock.json
- package.json
- src/components/Toast.tsx
- src/pages/Setting/FeedbackMail/FeedbackMail.tsx
- 피드백 이메일 EMAIL.JS 라이브러리 연결 (가장 안정적이라 선택)
- 토스트 컴포넌트 확장
- 없음
- 없음
> [FE-242] feat: 피드백 이메일 api 연동

- src/apis/auth.ts
- src/pages/Setting/Setting.tsx
- src/react-query/hooks/useUser.ts
> [FE-209] feat: 로그아웃 구현

- src/pages/Setting/FeedbackMail/FeedbackMail.tsx
- src/pages/Setting/TeamIntroduction/TeamIntroduction.tsx
- 팀소개 페이지 레이아웃 수정
- 피드백메일 페이지 인풋 글자수 초과 버그 수정
- 알럿 줄바꿈 수정
- 보내기 버튼 조정
- 메인페이지 글자색 고정
- 없음
- 없음
> [FE-254] fix: 팀소개, 피드백 메일 페이지 버그 수정

- src/pages/Setting/ManageComment/CommentSection.tsx
- src/pages/Setting/ManageComment/ManageComment.tsx
-내 댓글 관리페이지 개발
- ComeentSection 컴포넌트 분리
실제 api나오면 삭제와 연동까지 다 구현하려고해요! 자유롭게 리뷰 부탁드릴게용
> [FE-246]feat: 내 댓글 관리페이지 개발

- src/components/RankingItem.tsx
- src/pages/Setting/FeedbackMail/FeedbackMail.tsx
- src/pages/Setting/TeamIntroduction/TeamIntroduction.tsx
- 피드백 메일 제목 20글자 넘어가면 return 로직 추가. 
- 메인페이지 랭킹 폰트색 고정. 
- 팀소개 페이지 p태그 폰트 지정
- 없음
- 없음
> [FE-254] fix: 20글자 넘어가면 return 로직 추가. 메인페이지 랭킹 폰트색 고정. 팀소개 페이지 p태그 폰트 지정

- src/pages/AddRecord/AddRecordInput.tsx
-부모에 의존돼있던 값을 e.target.value로 수정
> [FE-239]fix: 12글자 넘어가면 입력가능함

- src/pages/Setting/ModifyInfo/ModifyInfo.tsx
- [[FE-255] fix: 닉네임 수정 정책서와 피그마대로 기능 수정](https://github.com/ItRecode/recodeIt-client/commit/54631a6798823135bd6d770b1f1ee6ee29a096ad)
- [[FE-255] feat: 내 정보 수정 뒤로가기 시 알럿 노출 구현](https://github.com/ItRecode/recodeIt-client/commit/8ee5f4053d1cc2e935df6b05c4061237089b4c81)
> [FE-255] feat: 내 정보 수정 정책 반영

- src/pages/Setting/FeedbackMail/FeedbackMail.tsx
- 인풋 Focus 보라색으로 변경
- 바디 200자 제한 추가
- 없음
- 없음
> fix: 피드백페이지 qa 반영

- src/assets/constant/ranking.ts
- src/pages/Collect/CollectRanking.tsx
- src/store/collectPageAtom.ts
- 모아보기 랭킹 기간 '기준' 문구 삭제
- 모아보기 랭킹 기간 초기값 누적으로 변경
- 없음
- 없음
> fix: 모아보기 랭킹 기간 변경

- src/pages/Setting/ModifyInfo/ModifyInfo.tsx
- url로 직접 닉네임 수정 페이지 접근 시 에러 버그 픽스
> [FE-259] fix: url로 직접 닉네임 수정 페이지 접근 시 에러 버그 픽스

- src/pages/Collect/CollectRanking.tsx
- 모아보기 페이지 하루 선택시 랭킹 기준 시간 추가
- 없음
> fix: 모아보기 랭킹 기준 시간 추가

- src/pages/Setting/FeedbackMail/FeedbackMail.tsx
> hotfix: 피드백메일 버튼 모바일 감지 추가

- src/pages/Setting/ManageComment/ManageComment.tsx
> [FE-250]fix: 내 댓글관리 로딩상태 추가

- src/pages/Setting/Setting.tsx
- src/pages/Setting/Withdraw/Withdraw.tsx
> [FE-244] feat: 탈퇴하기 첫 페이지 레이아웃 구현
