ItRecode/recodeIt-client

tailwind.config.js

- theme colors 추가
- tailwind theme colors 추가 (적용되는 것 확인함, intelligence 플러그인 사용시 자동완성에도 뜸)
- fontFamaily도 추가해서 일괄 적용하려고 했으나 sf pro display 글꼴 저작권 이슈 발생할 것 같아 우선 보류함
- 없음
- 없음

[FE-7] Style: tailwind theme 추가

---

src/assets/back.svg
src/components/BackButton.tsx
tsconfig.extend.json

assets 절대경로가 추가되지 않아서 이를 tsconfig에서 추가했고, 뒤로가기 버튼을 만들었는데 이때 svg파일을 figma에서 가져와서 저장
뒤로가기 라우팅을 즉시실행함수로 안하고 handle~로 했는데 즉시실행함수로 하는게 더 가독성이 좋을지 ?

[FE-18] assets 절대경로 추가,  뒤로가기 버튼 생성 아이콘 저장

---

.vscode/settings.json
package-lock.json
package.json

- prettier-plugin-tailwindcss 설치 / 셋팅
- prettier 랑 연계되어 tailwind 클래스명을 자동정렬해주는 플러그인이라 에디터 기본 포매터를 프리티어로 설정
- tailwind 권장 클래스 순서대로 정렬 (https://tailwindcss.com/blog/automatic-class-sorting-with-prettier#how-classes-are-sorted) 
- 없음
- 없음

[FE-22] prettier-plugin-tailwindcss 설치

---

src/App.tsx
src/components/Layout.tsx

- 레이아웃 추가
- 실제로 쓸 컨테이너는 350px로 고정해서 화면이 450px 넘어가면 350px의 컨테이너 화면과 배경색으로 분리된 느낌 (450px 전까지는 흰색으로 padding 느낌으로 처리)
- children 렌더링
- 449px 일때
- 450px 일때
- 이정도로 충분할까요? 그리고 컨테이너를 350px로 고정해놓는 것이 맞을지 의견 부탁드립니다.

[FE-20] feat: 레이아웃 추가

---

src/components/Layout.tsx
tailwind.config.js

- 레이아웃 적용 픽셀 수정
- 375px 로 고정해놨던 레이아웃을 375보다 작아지는 경우 스크린의 크기에 따라 작아지도록 수정하였습니다.
- 450px 이상인 경우 375px 고정, wrapper 컨테이너 배경색 있음
- 450px ~ 375px 인 경우 375고정, wrapper 컨테이너 배경색 없음
- 375px 이하인 경우 스크린 크기에 따라 width 변경  
- 없음
- 없음

[FE-20] fix: 레이아웃 수정

---

.eslintrc.js
src/index.css

- eslint `console.log`입력시 경고 표시
- 배포 시 콘솔로 데이터 유출 방지
```js
rules: {
'no-console': 'warn',
},
```
- index.css에 margin, padding 0 적용
아래와 같은 margin이 없도록 0으로 적용

[FE-30] chore: eslint no-console, index.css에 마진, 패딩 설정

---

src/components/MainCategoryTap.tsx
src/pages/AddRecord/AddRecord.tsx
src/pages/AddRecord/AddRecordInput.tsx

-원래 현재위로 탭 코드가 AddRecord파일에 의존되있었는데 해당 코드를 컴포넌트로 이관
AddRecord에 현재 위로 탭 코드 나누는걸 컴포넌트로 이관했습니다.
해당 컴포넌트를 사용할떄는 아래 사진처럼 꼭 위로/축하로 바뀔시 생성되는 함수를 props로 전달해주셔야되여
자유롭게 리뷰주세요 중점사항은 없습니다.

[FE-41]feat: 컴포넌트 이관

---

src/components/Button.tsx
src/components/Input.tsx
src/pages/SignUp/SignUp.tsx
src/routes/routes.tsx

- 닉네임 설정 페이지 레이아웃 구현(기능X)
- 버튼 default 일 때 inactive 배경 색 추가
- input 컴포넌트를 임시로 만들었고 디자인 시스템 나오면 보완해서 만들겠습니다!
`index.css`에 input 컴포넌트에 `border:none`이 설정되어 있는데 `border:inherit`으로 설정해도 괜찮을까요?
`border:none`이 설정되어있어서 border이 필요한 경우에 적용이 안됩니다!

[FE-34] feat: 회원가입(닉네임 설정 페이지)구현

---

src/assets/more.svg
src/components/MoreButton.tsx
src/index.css
src/pages/DetailRecord/DetailRecord.tsx

- 레코드 상세 페이지 레이아웃
- 기본 골격만 잡고 추후 컴포넌트 분리 및 데이터 변수 생성 예정
- 없음

[FE-40] feat: 레코드 상세 페이지 레이아웃 구성

---

src/apis/auth.ts
src/components/Input.tsx
src/hooks/useForm.ts
src/pages/SignUp/SignUp.tsx
src/react-query/hooks/useAuth.ts
src/react-query/hooks/useNickname.ts
src/react-query/queryKeys.ts

- handleChange, handleRemove, handleSubmit 으로 폼 관리
- error 핸들링 적용
- 오타, 함수명, 변수명 등 로직까지 모두 부탁드립니다 :)

[FE-33] feat: 닉네임 중복 기능 구현

---

src/pages/SignUp/SignUp.tsx
src/react-query/hooks/useNickname.ts

- 닉네임과 회원가입 로직 분리
- 현재 닉네임 중복 기능에 적용되어 있던 useForm훅이 회원가입 로직도 연결되어 있어서 안되었었음
- 따라서 회원가입은 따로 함수로 빼서 적용시키고 닉네임 중복 구현만 useForm 훅을 사용하도록 변경하였습니다!!
없습니당

[FE-70] fix: 닉네임 중복 구현 버그 픽스

---

src/pages/Login/GoogleButton.tsx
src/pages/Login/KakaoButton.tsx
tailwind.config.js

-  카카오/구글 버튼 아이폰에서만 파란색으로 보이는 버그 픽스
- 아이폰에서만 아래처럼 파란색으로 보여서 이 부분 픽스해서 올립니다
없습니다

[FE-86] fix: 카카오/구글 버튼 아이폰에서만 파란색으로 보이는 버그 픽스

---

src/assets/spinner.svg
src/components/Loading.tsx
src/components/Spinner.tsx

- 로딩 컴포넌트 구현
- Spinner 컴포넌트 구현
로딩 중 페이지가 필요할 경우에는 로딩 컴포넌트를, 단지 로딩 중인 것을 표시할 때에는 Spinner 컴포넌트를 사용하면 될 것 같습니당
없습니당

[FE-98] 로딩 컴포넌트 구현

---

src/routes/protectedRoute.tsx
src/routes/router.tsx

-쿠키내에 SESSION Value가 없으면 로그인페이지로 리다이렉트
지금 저희 실제 배포환경처럼 isPublic을 false로 줬는데 SESSION을 꼭 쿠키에 넣어주시거나 개발환경에서 임시로 isPublic을 true로 둔뒤 작업하시고 그부분 커밋 안하셔도 좋을것같아용

[FE-95]feat: protectedRoute 쿠키로 구현

---

src/pages/AddRecord/AddRecord.tsx

-formData에 파일에 undefined가 추가되면 파일 추가가 안되는 버그 수정

[FE-111]bug: 레코드 파일추가 안했을때 추가 안되는 버그 수정

---

src/pages/AddRecord/AddRecord.tsx

- 레코드 추가하기 버튼에 로딩 추가
- 레코드 추가한 후 replace적용으로 뒤로가기 안되도록 구현
없습니다

[FE-119] feat: 레코드 추가하기 버튼에 로딩 추가

---

src/apis/auth.ts
src/components/Button.tsx
src/pages/DetailRecord/DetailRecord.tsx
src/pages/DetailRecord/ImageContainer.tsx
src/pages/DetailRecord/ReplyInput.tsx
src/pages/DetailRecord/ReplyItem.tsx
src/pages/DetailRecord/ReplyList.tsx
src/pages/DetailRecord/getChipIconName.ts
src/pages/DetailRecord/getCreatedDate.ts

- 레코드 추가 후 상세페이지에서 ‘내편이 되어주세요’ 칩 이미지 안나오는 에러 수정
- 레코드 상세페이지 날짜 1.7 → 01.07 폼
- 댓글 100자 제한 placeholder 문구 추가
- 댓글 로딩 구현
- 댓글 이미지 인풋창 초기화
- 이미지 삽입 시 1:1 비율 구현
- 레코드 내용 라인하이츠 / 댓글 라인하이츠 수정
- 내가 쓴 글 외의 수정 버튼 안나오게 변경
- 없음
- 없음

[FE-130] fix : 레코드 상세 페이지 QA 에러 수정

---

src/apis/record.ts
src/hooks/useSwipe.ts
src/pages/MyRecord/MemoryRecord.tsx
src/pages/MyRecord/MemoryRecordItem.tsx
src/react-query/hooks/useMemoryRecord.ts
src/types/recordData.ts

- [fix: 수정된 memory API로 재적용](https://github.com/ItRecode/recodeIt-client/commit/5a4aae20557b2aac2f4bb1a8d12db1941bfb350d)
- [fix: 댓글 전체보기 4개 이상 있을 경우 넣기](https://github.com/ItRecode/recodeIt-client/commit/192ed0e10b8b59849c0eacb9357c4ea4c0fdcaae)
- [fix: 드래그 시 댓글 클릭 안되는 버그 픽스](https://github.com/ItRecode/recodeIt-client/commit/ebb05380e507da398fd1c5af806589d2b72b80d7)

[FE-153] refactor: 바뀐 추억 레코드 API 재적용과 Swipe 버그 픽스

---

src/pages/AddRecord/AddRecord.tsx
src/pages/AddRecord/AddRecordCategory.tsx
src/store/atom.ts

-해당 배열의 길이를 넘어가는 인덱스 대입시 화면 터지는 버그 수정
-수정 페이지 이동시 카테고리 변경안되는 버그 수정
-너무 많은 리렌더링 이슈로 recordType recoil로 이관
기존 추가후 레코드 수정도 되고, 위로일떄도 카테고리 잘 반영되는거 위에 확인부탁드릴게요!
리코일로 이관한 이유 자세하게 궁금하면 저한테 질문주세요!

[FE-156]fix: 수정 페이지 이동시 버그

---

src/pages/DetailRecord/ReplyInput.tsx
src/react-query/hooks/useAuth.ts
src/routes/protectedRoute.tsx

- 아래페이지에 적용
- 마이레코드 페이지
- 레코드 수정/추가 페이지
- 비댓글일 경우 댓글 클릭 후 회원가입 시
1. recoil로 전역 관리하려했으나 카카오/구글 회원가입 시 무조건 새로고침이 일어나게 됨
2. 따라서 LocalStorage로 관리

[FE-160] feat: 비회원일 경우 원래 페이지로 리다이렉트

---

src/pages/DetailRecord/ReplyList.tsx

- fix: 댓글 id값 없을 경우 스크롤 id값 초기화

[FE-159] fix: 댓글 id값 없을 경우 스크롤 id값 초기화

---

src/components/NavbarItem.tsx
src/pages/SignUp/SignUp.tsx

-  회원가입 이모지 안들어가도록 구현
- 네브바 탭 마이레코드 디자인 변경
- 레코드 입장 버튼 움직이지 않도록 고정
- 네브바 탭 맥 OS가 아닌 화면에서 아래처럼 나온다고 해서 디자인 w-max 넣음
- 적용이 안될 수도 있습니다..ㅠㅠ

[FE-165] feat: 회원가입 이모지 안들어가도록 구현

---

src/components/Chip.tsx
src/components/MainCategoryTap.tsx
src/pages/AddRecord/AddRecord.tsx
src/pages/AddRecord/AddRecordCategory.tsx

-수정모드일때 탭 회색처리
-수정모드일때 카테고리 회색처리

[FE-173]feat: 수정모드일때 수정불가능한것들 회색처리

---

src/apis/record.ts
src/hooks/useSwipe.ts
src/pages/Main/Main.tsx
src/pages/Main/TogethderSlider.tsx
src/pages/Main/Together.tsx
src/pages/Main/TogetherTab.tsx
src/types/recordData.ts

- 메인페이지 함께 축하해보세요 기능 구현
- swipe hook 약간 수정
- 탭 변경시 스크롤 초기화
- stale: Infinity 값을 주어 탭 변경해도 기존 아이템 유지되도록 구현함
- 스크롤 영역 전체가 cursor:pointer 로 지정되어 있어 클릭시 링크이동되는 영역 scale 1.1 로 구현했음
https://user-images.githubusercontent.com/88193063/216765363-b3279f9d-7eab-4f77-bbe5-5aa2d8bfda23.mov
- 링크 영역 scale 1.1 로 구현한거 괜찮은지?

[FE-184] feat: 메인페이지 함께 축하해보세요 기능 구현

---

src/components/ScrollTop.tsx
src/routes/router.tsx

- fix: 페이지 이동 시 스크롤 Top으로 이동 안되던 버그 픽스
- NavBar에 있는 4개의 페이지와 레코드 추가 페이지에만 적용하였습니다

[FE-189] fix: 페이지 이동 시 스크롤 Top으로 이동 안되던 버그 픽스

---

src/components/Card.tsx
src/components/RecordCard.tsx
src/pages/Main/TogetherSlider.tsx
src/types/recordData.ts

-중복 사용됨에 따라 Card컴포넌트화
-TogetherSlider에서 Card컴포넌트로 대체
free하게 남겨주세용~

[FE-214]feat: Card컴포넌트화

---

src/components/Category.tsx
src/pages/AddRecord/AddRecord.tsx
src/pages/AddRecord/AddRecordCategory.tsx
src/pages/AddRecord/AddRecordInput.tsx
src/pages/AddRecord/AddRecordTextArea.tsx

-레코드 추가 접근시 카테고리 안보임
-화면 나갔을떄 수정모드 안지워짐
-수정모드 접근시 제목이나 카테고리 안먹힘
-레코드 추가에서 탭 바꾸면 textArea 초기화안됨
-추가하기(수정하기)버튼 제대로 안먹힘
자유롭게 리뷰 부탁드려요!!!

[FE-213]fix: 레코드 추가페이지 버그 픽스

---

src/apis/myRecord.ts
src/apis/record.ts
src/components/Navbar.tsx
src/pages/MyRecord/Common/MemoryRecordCard.tsx
src/pages/MyRecord/Common/MyRecordCard.tsx
src/pages/MyRecord/Common/SearchInput.tsx
src/pages/MyRecord/MemoryRecord.tsx
src/pages/MyRecord/MyRecord.tsx
src/pages/MyRecord/Search/SearchRecord.tsx
src/pages/MyRecord/TodayRecord.tsx
src/react-query/hooks/useMemoryRecord.ts
src/react-query/hooks/useMyRecordByDate.ts
src/react-query/hooks/useMyRecordByKeyword.ts
src/react-query/hooks/useRecordByDate.ts
src/react-query/queryKeys.ts
src/routes/protectedRoute.tsx
src/routes/router.tsx
src/store/myRecordAtom.ts
src/types/myRecord.ts
src/types/recordData.ts
src/types/request.ts
src/types/response.ts

- 마이 레코드 페이지 Api와 타입 분리
- `myrecord/search`와 /myrecord/calendar`에 ProtectedRoute적용
- 검색 페이지 레이아웃 재적용과 API 연결
- 검색 무한 스크롤 구현
전체적으로 부탁드립니다
수정된 파일이 많지만 대부분 폴더구조와 이름 변경으로 인한 내용이 많습니다 :)

[FE-201] feat: 검색 페이지 API 연동과 myRecord 타입과 api 리팩토링

---

src/pages/DetailRecord/DetailRecord.tsx
src/pages/DetailRecord/InputSnackBar.tsx
src/pages/DetailRecord/InputTextarea.tsx
src/pages/DetailRecord/NestedReplyItem.tsx
src/pages/DetailRecord/ReplyInput.tsx
src/pages/DetailRecord/ReplyItem.tsx
src/pages/Main/Main.tsx
src/store/atom.ts
src/store/detailPageAtom.ts
src/store/mainPageAtom.ts

- 카테고리 ID 전역상태로 변경하여 ID 값 유지
- atom 정리
- 없음
- 없음

[FE-219] feat: 메인페이지 카테고리ID 유지 추가

---

src/assets/constant/constant.ts
src/pages/AddRecord/AddRecordInput.tsx
src/pages/MyRecord/Common/SearchInput.tsx
src/pages/MyRecord/MyRecord.tsx
src/pages/MyRecord/Search/SearchRecord.tsx

- fix: 검색 input 클릭 시 placeholder 제거
- fix: 검색 최대 12글자까지 검색할 수 있도록 수정

[FE-224] fix: 마이페이지 검색 QA 버그 픽스 

---

src/apis/record.ts
src/components/Category.tsx
src/components/RankingItem.tsx
src/components/RecordCard.tsx
src/pages/Collect/Collect.tsx
src/pages/Collect/CollectRanking.tsx
src/pages/Collect/RecentRecord.tsx
src/pages/DetailRecord/DetailRecord.tsx
src/pages/Main/Main.tsx
src/pages/Main/Ranking.tsx
src/store/collectPageAtom.ts
src/store/detailPageAtom.ts
src/store/mainPageAtom.ts

- 레코드 랭킹 옆에 버튼 디자인 조정
- 랭킹 아이템 전체 누르면 상세페이지 이동
- 믹스레코드 미모티콘 으로 다시 돌리기
- 레코드카드 두줄일때 디자인 반영
- 상세페이지에서 뒤로가기 해서 이동 시 카테고리 / 기간 설정 유지
- 모아보기 페이지 총 레코드 갯수 api 연결 
- 없음
- 없음

[FE-229] fix: 메인페이지 & 랭킹 QA 피드백 반영

---

src/pages/MyRecord/Common/SearchInput.tsx

[FE-230] fix: 검색 input 포커스 해제 시 placeholder 초기화 버그 픽스
[FE-230]: https://recodeit.atlassian.net/browse/FE-230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FE-230] fix: 검색 input 포커스 해제 시 placeholder 초기화 버그 픽스

---

src/components/Chip.tsx
src/pages/Collect/CollectRanking.tsx
src/pages/Main/RankingList.tsx

- 카테고리 스크롤 유지 기능 추가
- 스크롤(좌우) 기억 추가
https://user-images.githubusercontent.com/88193063/220933582-3167cbd4-72b7-477d-a25d-a63299945f29.mov
- 최신 레코드에서 상세 페이지로 넘어갔다와도 카테고리에서 스크롤 걸림
https://user-images.githubusercontent.com/88193063/220933624-d26e46f9-ca33-4ff7-b3af-a3fcb7854c20.mov
- 모아보기 페이지에서 최신 레코드의 스크롤탑 기능이랑 충돌하는데 어떻게 해야할까요?

[FE-249] feat: 카테고리 스크롤 유지 추가

---

src/pages/Setting/Setting.tsx
src/routes/router.tsx

- 설정 페이지 라우팅 변경
- 설정 페이지 하위 목록 페이지를 설정페이지의 children 으로 변경
- 설정 페이지에서만 navbar 가 쓰여서 공통 엘리먼트에서 navbar 삭제후 설정페이지에서만 쓰이도록 변경함
- 없음
- 없음

fix: 설정 페이지 라우팅 변경

---

src/apis/myRecord.ts
src/pages/MyRecord/Calendar/Calendar.tsx
src/pages/MyRecord/Calendar/CalendarMonthYear.tsx
src/pages/MyRecord/Calendar/CalendarRecord.tsx
src/pages/MyRecord/Calendar/DateBox.tsx
src/pages/MyRecord/MyRecord.tsx
src/react-query/hooks/useMemoryRecord.ts
src/react-query/hooks/useMyRecordByMonthYear.ts

- 달력 캘린더 년/월/일 선택 시 추억 레코드 리스트 가져오도록 구현
- 추억레코드와 마찬가지로 더보기 버튼으로 추가적으로 가져오도록 함
- 웬만한 버그는 고쳐놓았는데 제가 찾지 못한 버그가 있을 수 있을 것 같아요ㅠㅠ

[FE-234] feat: 추억레코드 캘린더 API 연동 구현

---

src/pages/Setting/ModifyInfo/ModifyInfo.tsx

- 닉네임 수정 중복검사 추가
- 기존 닉네임이 없을 때 수정 페이지에 들어올 경우 setting페이지로 리다이렉트 시킴

[FE-258] fix: 닉네임 수정 중복검사 추가

---

src/components/Alert.tsx
src/pages/Setting/Setting.tsx
src/pages/Setting/Withdraw/CheckedNicknameBeforeWithDraw.tsx
src/pages/Setting/Withdraw/Withdraw.tsx
src/routes/router.tsx

- 탈퇴하기 닉네임 일치 구현
- 탈퇴하기 -> 라우트 구현
- 탈퇴하기 누를 경우 탈퇴하시겠습니까 알럿 구현
- 아직 개발 서버에 api가 배포되지 않아 연동은 하지 않았습니다.

[FE-252] feat: 탈퇴하기 닉네임 일치 구현
